### ISSUE TITLE
Colors table

### ISSUE THREAD

**Issue by bocianu** [jewettg/Neo6502-Documentation#17]
![image](https://github.com/user-attachments/assets/22c7104c-24b8-4289-a9b6-426111b7853f)

Taking pictures of an LCD screen is probably not a good idea if you want to reproduce colors accurately. Instead, I recommend using the actual color representations based on their RGB values. I've already applied this approach in the neo6502 documentation, which you can find here:

![image](https://github.com/user-attachments/assets/c8d28a5c-7f05-4a38-bacb-75a38ae312b9)

https://www.neo6502.com/reference/graphics/

Below, you can find the RGB values for the default neo palette:

| Color  | RGB Hex |
|--------|-------------|
| Color0 | #000000     |
| Color1 | #ff0044     |
| Color2 | #00ee33     |
| Color3 | #ffee22     |
| Color4 | #112255     |
| Color5 | #772255     |
| Color6 | #22aaff     |
| Color7 | #ffffee     |
| Color8 | #000000     |
| Color9 | #555544     |
| Color10 | #008855    |
| Color11 | #ffaa00    |
| Color12 | #aa5533    |
| Color13 | #887799    |
| Color14 | #ffccaa    |
| Color15 | #cccccc    |

**Comment by jewettg** [comment]
Updated.  Thanks!
