### ISSUE TITLE
PDF - page 7 remark

### ISSUE THREAD

**Issue by bocianu** [jewettg/Neo6502-Documentation#19]
![image](https://github.com/user-attachments/assets/099e5773-382f-41fc-ad59-98396dffbcf0)

Not all the firmwares are emulators, so perhaps we should replace the word 'emulators' with 'firmwares' in the documentation?

**Comment by jewettg** [comment]
This has been fixed.  Thanks.  Will show up as of 2024-08-30, before noon CST.
